Repository money-driven-development/rocket23, pull requests merged in 2023-06, with the labels that each got.

#18 [IC-24] feat: 도커 컨테이너 관리 기능 구현
  build.gradle
  docker/src/main/java/com/initcloud/dockerapi/common/enums/ResponseCode.java
  docker/src/main/java/com/initcloud/dockerapi/container/annotation/ContainerLifeCycle.java
  docker/src/main/java/com/initcloud/dockerapi/container/aspect/ContainerOrchestrationAspect.java
  docker/src/main/java/com/initcloud/dockerapi/container/client/ContainerApi.java
  docker/src/main/java/com/initcloud/dockerapi/container/controller/DockerContainerController.java
  docker/src/main/java/com/initcloud/dockerapi/container/controller/DockerContainerInspectController.java
  docker/src/main/java/com/initcloud/dockerapi/container/controller/DockerContainerManageController.java
  docker/src/main/java/com/initcloud/dockerapi/container/dto/ContainerDto.java
  docker/src/main/java/com/initcloud/dockerapi/container/dto/ContainerInspectDto.java
  docker/src/main/java/com/initcloud/dockerapi/container/enums/ContainerAPIType.java
  docker/src/main/java/com/initcloud/dockerapi/container/enums/ContainerLifeCycleStrategy.java
  docker/src/main/java/com/initcloud/dockerapi/container/enums/ContainerStatus.java
  docker/src/main/java/com/initcloud/dockerapi/container/event/ContainerInitializationListener.java
  docker/src/main/java/com/initcloud/dockerapi/container/middleware/ContainerApi.java
  docker/src/main/java/com/initcloud/dockerapi/container/middleware/ContainerStrategyApi.java
  docker/src/main/java/com/initcloud/dockerapi/container/middleware/DockerContainerApi.java
  docker/src/main/java/com/initcloud/dockerapi/container/service/ContainerInspectService.java
  docker/src/main/java/com/initcloud/dockerapi/container/service/ContainerManageService.java
  docker/src/main/java/com/initcloud/dockerapi/container/service/DockerInspectService.java
  docker/src/main/java/com/initcloud/dockerapi/container/service/DockerManageService.java
  docker/src/main/java/com/initcloud/dockerapi/container/service/DockerService.java
  docker/src/main/java/com/initcloud/dockerapi/redis/client/RedisContainerQueueClient.java
  docker/src/main/java/com/initcloud/dockerapi/redis/config/RedisConfig.java
  docker/src/main/resources/application.yml
  file/src/main/java/com/initcloud/rocket23/FileApiApplication.java
Labels: feature-functional

#22 [IC-33] fix: 압축파일 업로드 식별 및 압축파일 해제
  file/src/main/java/com/initcloud/rocket23/common/config/S3Config.java
  file/src/main/java/com/initcloud/rocket23/common/enums/ResponseCode.java
  file/src/main/java/com/initcloud/rocket23/file/service/FileService.java
  file/src/main/java/com/initcloud/rocket23/file/service/Impl/FileServiceImpl.java
Labels: feature-functional

#23 [IC-27] feat: DockerAPI의 Redis 스트림 처리를 위한 Pub/Sub 구현
  build.gradle
  docker/build.gradle
  docker/src/main/java/com/initcloud/dockerapi/DockerApiApplication.java
  docker/src/main/java/com/initcloud/dockerapi/container/aspect/ContainerOrchestrationAspect.java
  docker/src/main/java/com/initcloud/dockerapi/container/aspect/MessageStreamAspect.java
  docker/src/main/java/com/initcloud/dockerapi/container/client/DockerClientConfigBuilder.java
  docker/src/main/java/com/initcloud/dockerapi/container/client/DockerContainerHttpClient.java
  docker/src/main/java/com/initcloud/dockerapi/container/controller/DockerContainerInspectController.java
  docker/src/main/java/com/initcloud/dockerapi/container/controller/DockerContainerManageController.java
  docker/src/main/java/com/initcloud/dockerapi/container/dto/ContainerDto.java
  docker/src/main/java/com/initcloud/dockerapi/container/dto/ContainerInspectDto.java
  docker/src/main/java/com/initcloud/dockerapi/container/enums/ContainerAPIType.java
  docker/src/main/java/com/initcloud/dockerapi/container/event/ContainerInitializationListener.java
  docker/src/main/java/com/initcloud/dockerapi/container/middleware/ContainerStrategyApi.java
  docker/src/main/java/com/initcloud/dockerapi/container/middleware/DockerContainerApi.java
  docker/src/main/java/com/initcloud/dockerapi/redis/client/RedisContainerQueueClient.java
  docker/src/main/java/com/initcloud/dockerapi/redis/config/RedisClientConfig.java
  docker/src/main/java/com/initcloud/dockerapi/redis/config/RedisPubSubConfig.java
  docker/src/main/java/com/initcloud/dockerapi/redis/config/RedisStreamConfig.java
  docker/src/main/java/com/initcloud/dockerapi/redis/enums/Channels.java
  docker/src/main/java/com/initcloud/dockerapi/redis/message/ScanStreamMessage.java
  docker/src/main/java/com/initcloud/dockerapi/redis/pubsub/RedisMessagePublisher.java
  docker/src/main/java/com/initcloud/dockerapi/redis/pubsub/RedisMessageSubscriber.java
  docker/src/main/java/com/initcloud/dockerapi/redis/stream/RedisMessageStreamConsumer.java
  docker/src/main/java/com/initcloud/dockerapi/redis/stream/RedisMessageStreamProducer.java
  docker/src/test/java/com/initcloud/dockerapi/container/controller/DockerContainerInspectControllerTest.java
Labels: feature-functional

#24 [IC-22] chore: 깃허브 CI 파이프라인 구성
  .github/workflows/pipeline-module-docker.yaml
  .github/workflows/pipeline-module-file.yaml
  .github/workflows/template-git-leaks.yaml
  .github/workflows/template-gradle-build.yaml
  .github/workflows/yaml-lint.yaml
Labels: feature-non-functional

#26 [IC-49] feat: Restdocs 모듈 구현
  build.gradle
  restdocs/build.gradle
  restdocs/src/main/java/com/initcloud/rocket23/RestDocsApplication.java
  restdocs/src/test/java/com/initcloud/rocket23/RestDocsApplicationTest.java
  settings.gradle
Labels: documentation, feature-functional
